# Copyright (C) 2005-2009, The Perl Foundation.
# $Id$

=head1 Using Lua on Parrot

=head2 In brief

C<lua.pbc> is the Lua interpreter.

=head2 Building

After building C<parrot> (see F<docs/gettingstarted.pod>):

  cd languages/lua
  make

=head2 Running the whole test suite

  make test

=head2 Testing the test suite

With an original C<Lua> in your path, it's possible to check the test suite.

  perl t/harness --use-lua

=head2 Running your own code

  ../../parrot lua.pbc example.lua

or in interactive mode :

  ../../parrot lua.pbc

=head2 Bugs & Limitations

See F<languages/lua/doc/status.pod>

=head2 See Also

F<languages/lua/doc/status.pod>

=head2 Author

Francois Perrad.

=cut

# Local Variables:
#   fill-column:78
# End:
# vim: expandtab shiftwidth=4:
