# Copyright (C) 2007, The Perl Foundation.
# $Id$

=head1 Metacommitter Guide

From F<docs/project/roles_responsibilities.pod>:

 All Metacommitters are responsible for managing commit access to the Parrot
 repository. Once the Architect or Pumpking approves a request for a
 Contributor to be given commit access, a Metacommitter provides that access.
 The Architect and Pumpking are Metacommitters, but other Project Team members
 may also hold this role.

The procedure below describes how to manage the list of Parrot committers.

=head2 Instructions the new committer must follow

This procedure must be performed by the new committer before
the Metacommitter can add commit rights.

=over 4

=item 1

Create a bitcard.org id with the username you'd like to use

=item 2

Login to L<https://rt.perl.org/rt3/> with the id, so the user name is available
in RT for assigning tickets, and so it is registered in the list of users
eligible for parrot commit bit. Your login id is shown at the top of the 
page, e.g. C<Logged in as coke>. B<This> is the id you must provide to the
metacommitter so they can add you.

=item 3

Go to L<https://svn.perl.org/accounts/> and follow the directions there to
setup an svn password for your bitcard account; while the id is the same,
the passwords are separate.

=back

=head2 Instructions for the Metacommitter

The new committer must perform the above procedure before
the Metacommitter can add commit rights.

=over 4

=item 1

Login to RT at L<https://rt.perl.org/rt3/>

=item 2

Navigate to the Parrot Commit group,
L<https://rt.perl.org/rt3/Admin/Groups/Members.html?id=178234>

=item 3

Select the username from the "Add members" listbox, and select
"Modify Members" button

=back

Congratulate the new member publicly by sending an email to
parrot-dev@lists.parrot.org, and copying the new committer.

=head2 To manage the list of Metacommitters

Only existing Metacommitters can perform this activity.

=over 4

=item 1

navigate to L<https://rt.perl.org/rt3/Admin/Groups/Members.html?id=178219>
and add/remove users as desired.

=back 

=head2 To manage the list of Bug Admins.

Only existing Metacommitters can perform this activity.

=over 4

=item 1

navigate to L<https://rt.perl.org/rt3/Admin/Groups/Members.html?id=20479>
and add/remove users as desired. Be sure to verify that the userid is the
one the user shows as logged in as. (Some bugadmins have multiple RT accounts.)

=back

=head1 AUTHOR

Jerry Gay a.k.a. particle

=head1 SEE ALSO

F<docs/project/roles_responsibilities.pod>, F<RESPONSIBLE_PARTIES>

=cut
