#! perl

# $Id$

=head1 NAME

languages/jako/t/harness - A harness for Jako 

=head1 SYNOPSIS

  cd languages && perl -I../lib jako/t/harness --files

=head1 DESCRIPTION

If I'm called with a single
argument of "--files", I just return a list of files to process.
This list is one per line, and is relative to the languages dir.

=cut

use Parrot::Test::Harness language => 'jako';
