# Copyright (C) 2001-2012, Parrot Foundation.

=pod

=head1 NAME

compilers/tge/README.pod - Tree Grammar Engine (TGE)

=head1 DESCRIPTION

TGE is a tool for transforming trees. It's most heavily used in the
compiler tools suite, where it transforms the trees output by PGE into
abstract syntax trees.

=head1 INSTALLATION

Compile TGE to bytecode and run its test suite:

  $ make
  $ make test

=cut

