#line 2 "imclexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
static yyconst short int yy_accept[291] =
    {   0,
        0,    0,    0,    0,    0,    0,   80,   68,   67,    1,
       67,   68,   68,   68,   68,   68,   68,   68,   68,   53,
       68,   58,   58,   42,   68,   44,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   68,
       68,   68,   68,   56,   56,   68,   78,   75,   70,   75,
       78,   78,   78,   78,   78,   58,   58,   76,   74,   74,
       67,    1,   47,    0,   61,    0,    0,    2,    0,    0,
        0,    0,    0,   39,    0,   62,   48,   58,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   57,    0,    0,
       36,   43,   46,   45,   37,   56,   54,    5,   56,   56,

       56,   56,   56,   56,   56,   56,   21,   56,   56,   56,
       56,   56,   56,   40,   41,   55,   55,   55,   52,   56,
        5,   55,   75,   70,   75,    0,    0,    0,    0,    0,
        0,   77,   77,   77,   76,   74,   74,   61,   63,   64,
       66,   65,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   57,    0,   60,   59,   38,    5,   56,
       56,   56,   25,   56,   19,   56,   56,   56,   24,   23,
       27,   56,   56,   56,   56,   55,   55,   55,   51,    5,
       55,    0,   71,   63,   64,   66,   65,   73,   77,   77,
       77,    7,   55,   55,    9,   55,   55,   55,   55,   55,

        8,    6,    0,   57,   29,   33,   56,   56,   56,   56,
       20,   56,   56,   56,   56,   55,   55,   55,   55,   73,
       77,   77,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   31,   56,   26,   56,   56,   56,   56,   56,   55,
       55,   55,    4,   69,   77,   12,   17,   55,   55,   16,
       55,   18,   55,   55,   56,   30,   56,   56,   32,   22,
        3,   55,   49,   77,   55,   55,   55,   10,   11,   28,
       56,   34,   55,   72,   55,   55,   55,   56,   50,   13,
       55,   55,   56,   55,   14,   35,   55,   55,   15,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    1,    9,   10,    1,
        1,   11,   12,   13,   12,   14,    1,   15,   16,   17,
       17,   17,   17,   17,   17,   17,   17,   18,    1,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       24,   24,   25,   24,   24,   24,   24,   26,   24,   27,
       24,   24,   28,   24,   24,   24,   24,   24,   24,   24,
        1,   29,    1,    1,   24,    1,   30,   31,   32,   33,

       34,   35,   36,   24,   37,   24,   24,   38,   39,   40,
       41,   42,   24,   43,   44,   45,   46,   47,   48,   49,
       50,   24,    1,   51,    1,   52,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    5,    1,    1,
        1,    6,    6,    7,    7,    7,    7,    7,    1,    6,
        6,    6,    6,    6,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        1,    1
    } ;

static yyconst short int yy_base[306] =
    {   0,
        0,  654,   52,  653,  104,  155,  666,  669,  156,  669,
      159,  645,  158,  162,  142,  655,  653,  651,  156,  669,
      158,  160,  164,  163,  641,  164,  642,  188,  175,  177,
      176,  171,  179,  181,  194,  196,  198,  195,  202,  608,
      606,  213,  184,  210,  244,  199,  669,  246,  669,  261,
      225,  241,  647,  255,  250,  259,  263,    0,  279,  283,
      222,  669,  669,  283,  669,  285,  289,  669,  291,  281,
      284,  287,  290,  669,  646,  669,  669,  301,    0,  612,
      203,  614,  612,  622,  621,  616,  189,  304,  294,    0,
      669,  669,  669,  669,  628,  630,  669,  307,  293,  295,

      310,  311,  312,  313,  314,  316,  629,  317,  318,  319,
      321,  322,  326,  669,  669,  302,  606,  615,  626,  219,
      342,  602,  367,  669,  370,  624,  360,  364,  368,  372,
        0,    0,  601,  599,    0,  389,  392,  391,  383,  386,
      389,  392,    0,  603,  608,  597,  603,  603,  595,  590,
      303,  601,  592,  395,  407,  337,    0,  669,  612,  395,
      396,  397,  611,  398,  610,  403,  399,  407,  609,  608,
      607,  408,  409,  410,  418,  587,  591,  590,  669,  423,
      582,  602,  669,  439,  443,  447,  451,    0,    0,  586,
      586,    0,  573,  572,  400,  585,  580,  583,  566,  565,

        0,    0,  429,  434,  592,  591,  452,  453,  454,  455,
      590,  456,  457,  458,  459,  562,  568,  562,  601,    0,
      564,  572,  557,  555,  561,  568,  559,  552,  556,  556,
      550,  574,  460,  573,  462,  461,  463,  466,  464,  585,
      538,  534,  669,    0,  533,    0,    0,  537,  524,    0,
      520,    0,  497,  488,  472,  507,  473,  471,  506,  505,
      669,  489,    0,  508,  477,  486,  489,    0,    0,  500,
      465,  499,  481,  509,  470,  448,  456,  478,    0,    0,
      400,  405,  488,  337,    0,  338,  214,  152,    0,  669,
      526,  533,  540,  542,  546,  551,  553,  558,  562,  566,

      570,  573,  575,  579,  583
    } ;

static yyconst short int yy_def[306] =
    {   0,
      290,    1,  290,    3,  290,    5,  290,  290,  290,  290,
      290,  290,  291,  292,  290,  290,  293,  290,  290,  290,
      294,  290,  290,  290,  290,  290,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  290,
      290,  294,  294,  296,  296,  294,  290,  290,  290,  290,
      291,  297,  293,  290,  298,  290,  290,  299,  290,  290,
      290,  290,  290,  291,  290,  291,  292,  290,  292,  290,
      290,  290,  290,  290,  293,  290,  290,  290,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  290,  290,  301,
      290,  290,  290,  290,  290,  295,  290,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  290,  290,  300,  300,  300,  290,  296,
      296,  300,  290,  290,  290,  302,  302,  302,  302,  302,
      303,  304,  304,  304,  299,  290,  290,  291,  290,  290,
      290,  290,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  290,  290,  290,  301,  290,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  300,  300,  300,  290,  296,
      300,  302,  290,  302,  302,  302,  302,  305,  304,  304,
      304,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  290,  290,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  300,  300,  300,  300,  305,
      304,  304,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  295,  295,  295,  295,  295,  295,  295,  295,  300,
      300,  300,  290,  304,  304,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  295,  295,  295,  295,  295,  295,
      290,  300,  300,  304,  300,  300,  300,  300,  300,  295,
      295,  295,  300,  290,  300,  300,  300,  295,  300,  300,
      300,  300,  295,  300,  300,  295,  300,  300,  300,    0,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290
    } ;

static yyconst short int yy_nxt[722] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   23,    8,   24,   25,
       26,   27,   27,   27,   28,   28,   28,   28,    8,   29,
       27,   30,   31,   32,   33,   34,   35,   27,   27,   36,
       27,   27,   37,   38,   27,   39,   27,   27,   27,   27,
       40,   41,    8,    9,   10,   11,    8,   13,   14,   15,
        8,   17,    8,   19,   20,   43,   22,   23,   23,    8,
        8,    8,    8,   44,   44,   44,   45,   45,   45,   45,
        8,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,    8,    8,   47,   48,   49,   50,   47,   51,
       47,   52,   47,   53,   47,   54,   47,   55,   56,   57,
       57,   47,   47,   47,   47,   58,   58,   58,   58,   58,
       58,   58,   47,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   47,   47,   59,   61,   60,   61,
       61,   62,   61,   65,   68,   69,   70,   71,   72,   73,
       78,   78,   78,   88,   78,   78,   78,   88,   78,   78,
       78,   91,   92,   94,   95,  289,   66,   80,   97,   81,
       89,   82,   97,   97,   97,   83,   97,   84,   97,   85,

       86,   87,   98,   98,   98,   97,  100,   99,   90,  102,
      103,   97,   97,   97,  101,   97,  104,  119,  105,   97,
      117,  106,  118,   61,  111,   61,  119,   97,  107,  109,
       65,  110,  122,  108,  152,  117,   97,  118,  153,  112,
      145,  113,   80,  146,   81,  288,  116,  123,  124,  125,
       83,  119,   84,   66,   85,   86,   87,  131,  121,  121,
      121,   97,  123,  124,  125,  127,  128,  129,  130,   78,
       78,   78,   88,   78,   78,   78,   88,   78,   78,   78,
      136,  124,  137,  133,  136,  124,  137,  134,   65,   89,
      138,   68,   69,   68,   69,  139,  139,  139,  140,  140,

      140,  141,  141,  141,  142,  142,  142,   90,  156,  156,
       97,   66,   97,   66,   88,   78,   78,   78,  154,  154,
      154,  159,  159,  159,   97,  160,  155,   97,   97,   97,
       97,   97,  161,   97,   97,   97,   97,  155,   97,   97,
      176,  147,  163,   97,  165,  164,  199,  200,  169,  119,
      162,  156,  156,  166,  167,   97,  180,  180,  180,   97,
      168,  170,  172,  175,  174,  171,  287,  173,  123,  124,
      125,  123,  124,  125,  184,  184,  184,  183,  185,  185,
      185,  183,  186,  186,  186,  183,  187,  187,  187,  183,
      136,  124,  137,  136,  124,  137,   65,  139,  139,  139,

      140,  140,  140,  141,  141,  141,  142,  142,  142,  154,
      154,  154,   97,   97,   97,   97,   97,  155,  203,   66,
       97,  204,  204,  204,   97,   97,   97,   97,  155,  210,
      119,  225,  209,  206,  208,   97,  207,  205,  285,  226,
       97,  284,  213,  204,  204,  204,  214,  211,  204,  204,
      204,  215,  212,  184,  184,  184,  183,  185,  185,  185,
      183,  186,  186,  186,  183,  187,  187,  187,  183,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,  235,  232,  237,  282,   97,   97,
       97,  281,  233,  255,  278,   97,  236,  238,  234,  256,

      258,  259,  239,  257,  270,   97,  271,  260,  272,  274,
      274,  274,  274,  280,  279,  283,   97,   97,  277,  276,
      275,  273,   97,   97,   97,  286,   64,  269,   64,   64,
       64,   64,   64,   67,   67,   67,   67,   67,   67,   67,
       75,  268,   75,   75,   75,   75,   75,   79,   79,   96,
       96,   96,   96,  120,  120,  120,  120,  120,  126,  126,
      132,  267,  266,  132,  132,  135,  265,  135,  135,  143,
      264,  143,  143,  157,  263,  157,  182,  182,  182,  182,
      188,  188,  189,  262,  189,  189,  220,  261,  220,  220,
       97,   97,  254,  253,  252,  251,  250,  249,  248,  247,

      246,  245,  244,  243,  242,  241,  240,   97,   97,   97,
      231,  230,  229,  228,  227,  224,  223,  222,  221,  183,
      219,  218,  217,  216,   97,   97,   97,   97,   97,   97,
      202,  201,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  183,  181,  179,  178,  177,   97,   97,  158,  151,
      150,  149,  148,  147,  144,   76,   76,  115,  114,   97,
       93,   77,   76,   74,   63,  290,   46,   42,    7,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290
    } ;

static yyconst short int yy_chk[722] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    6,    9,    6,    9,
       11,   11,   11,   13,   14,   14,   15,   15,   15,   15,
       19,   19,   19,   22,   22,   22,   22,   23,   23,   23,
       23,   24,   24,   26,   26,  288,   13,   21,   32,   21,
       22,   21,   29,   31,   30,   21,   33,   21,   34,   21,

       21,   21,   28,   28,   28,   28,   30,   29,   22,   31,
       32,   35,   38,   36,   30,   37,   33,   44,   34,   39,
       43,   34,   43,   61,   38,   61,  120,   44,   35,   36,
       51,   37,   46,   35,   87,   46,  120,   46,   87,   38,
       81,   39,   42,   81,   42,  287,   42,   48,   48,   48,
       42,   45,   42,   51,   42,   42,   42,   55,   45,   45,
       45,   45,   50,   50,   50,   52,   52,   52,   52,   54,
       54,   54,   56,   56,   56,   56,   57,   57,   57,   57,
       59,   59,   59,   55,   60,   60,   60,   55,   64,   56,
       66,   67,   67,   69,   69,   70,   70,   70,   71,   71,

       71,   72,   72,   72,   73,   73,   73,   56,   89,   89,
       99,   64,  100,   66,   78,   78,   78,   78,   88,   88,
       88,   98,   98,   98,   98,   99,   88,  101,  102,  103,
      104,  105,  100,  106,  108,  109,  110,   88,  111,  112,
      116,  116,  102,  113,  103,  102,  151,  151,  108,  121,
      101,  156,  156,  104,  105,  286,  121,  121,  121,  121,
      106,  108,  110,  113,  112,  109,  284,  111,  123,  123,
      123,  125,  125,  125,  127,  127,  127,  127,  128,  128,
      128,  128,  129,  129,  129,  129,  130,  130,  130,  130,
      136,  136,  136,  137,  137,  137,  138,  139,  139,  139,

      140,  140,  140,  141,  141,  141,  142,  142,  142,  154,
      154,  154,  160,  161,  162,  164,  167,  154,  155,  138,
      166,  155,  155,  155,  168,  172,  173,  174,  154,  167,
      180,  195,  166,  161,  164,  175,  162,  160,  282,  195,
      180,  281,  173,  203,  203,  203,  174,  168,  204,  204,
      204,  175,  172,  184,  184,  184,  184,  185,  185,  185,
      185,  186,  186,  186,  186,  187,  187,  187,  187,  207,
      208,  209,  210,  212,  213,  214,  215,  233,  236,  235,
      237,  239,  271,  238,  210,  207,  213,  277,  258,  255,
      257,  276,  208,  233,  271,  278,  212,  214,  209,  235,

      237,  238,  215,  236,  255,  283,  257,  239,  258,  264,
      274,  264,  274,  275,  273,  278,  272,  270,  267,  266,
      265,  262,  260,  259,  256,  283,  291,  254,  291,  291,
      291,  291,  291,  292,  292,  292,  292,  292,  292,  292,
      293,  253,  293,  293,  293,  293,  293,  294,  294,  295,
      295,  295,  295,  296,  296,  296,  296,  296,  297,  297,
      298,  251,  249,  298,  298,  299,  248,  299,  299,  300,
      245,  300,  300,  301,  242,  301,  302,  302,  302,  302,
      303,  303,  304,  241,  304,  304,  305,  240,  305,  305,
      234,  232,  231,  230,  229,  228,  227,  226,  225,  224,

      223,  222,  221,  219,  218,  217,  216,  211,  206,  205,
      200,  199,  198,  197,  196,  194,  193,  191,  190,  182,
      181,  178,  177,  176,  171,  170,  169,  165,  163,  159,
      153,  152,  150,  149,  148,  147,  146,  145,  144,  134,
      133,  126,  122,  119,  118,  117,  107,   96,   95,   86,
       85,   84,   83,   82,   80,   75,   53,   41,   40,   27,
       25,   18,   17,   16,   12,    7,    4,    2,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "imcc.l"
#define INITIAL 0
#line 2 "imcc.l"
/*
 * imc.l
 *
 * Intermediate Code Compiler for Parrot
 *
 * Copyright (C) 2002 Melvin Smith
 *
 * The tokenizer.
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "imc.h"
#include "parser.h"

#define MAX_PARAM 16

struct params_t {
    char *name[MAX_PARAM];
    int num_param;
};

struct macro_t {
    char *name;
    struct params_t params;
    char *expansion;
};

/* XXX: boe: rework this hack to use a hash */
struct macro_t macros[256];
int num_macros = 0;

char temp_buffer[4096];

struct macro_frame_t {
    struct macro_frame_t *next;
    YY_BUFFER_STATE buffer;
    struct params_t *params;
    struct params_t expansion;
    int label;
};

struct macro_frame_t *frames = NULL;

/* static function declariations */
static struct macro_frame_t *new_frame (void);
/*static void add_param_to_frame (const char *param, const char *expansion); */
static void scan_string (struct macro_frame_t *frame, const char *expansion);
static void scan_file (struct macro_frame_t *frame, FILE *);
static void destroy_frame (struct macro_frame_t *frame);
static int yylex_skip (YYSTYPE *valp, void *interp, const char *skip);

static int read_macro (YYSTYPE *valp, void *interp);
static int expand_macro (YYSTYPE *valp, void *interp, const char *name);
static void include_file (const char *file_name);

#define YY_DECL int yylex(YYSTYPE *valp, struct Parrot_Interp *interp)

#define YYCHOP() (yytext[--yyleng] = '\0')
#define DUP_AND_RET(valp, token)             \
  do {                                       \
      if (valp) (valp)->s = str_dup(yytext); \
      return token;                          \
  } while (0)

#define emit 1

#define macro 2

#line 695 "imclexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 91 "imcc.l"

        /* for emacs "*/
        if (expect_pasm == 1) {
            expect_pasm = 2;
            BEGIN(emit);
        }
        if (pasm_file && YYSTATE == INITIAL) {
            if (pasm_file == 1) {
                BEGIN(emit);
                return EMIT;
	    }
            return 0;
        }

#line 864 "imclexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 291 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 669 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 105 "imcc.l"
{
        if (expect_pasm == 2)
	  BEGIN(INITIAL);
        expect_pasm = 0;
        if (frames) line++;
        return '\n';
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 113 "imcc.l"
{
        if (expect_pasm == 2)
	  BEGIN(INITIAL);
        expect_pasm = 0;
        line++;
        return '\n';
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 122 "imcc.l"
{
	BEGIN(emit);
	return(EMIT);
    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 127 "imcc.l"
{
	BEGIN(INITIAL);
	return EOM;
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 132 "imcc.l"
{
	valp->s = str_dup(yytext);
	return REG;
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 137 "imcc.l"
return(LOCAL);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 138 "imcc.l"
return(ARG);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 139 "imcc.l"
return(SUB);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 140 "imcc.l"
return(ESUB);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 141 "imcc.l"
return(RESULT);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 142 "imcc.l"
return(RETURN);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 143 "imcc.l"
return(CLASS);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 144 "imcc.l"
return(ENDCLASS);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 145 "imcc.l"
return(NAMESPACE);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 146 "imcc.l"
return(ENDNAMESPACE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 147 "imcc.l"
return(LOCAL);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 148 "imcc.l"
return(CONST);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 149 "imcc.l"
return(PARAM);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 150 "imcc.l"
return(END);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 151 "imcc.l"
return(GOTO);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 152 "imcc.l"
return(IF);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 153 "imcc.l"
return(UNLESS);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 154 "imcc.l"
return(INTV);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 155 "imcc.l"
return(INC);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 156 "imcc.l"
return(DEC);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 157 "imcc.l"
return(FLOATV);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "imcc.l"
return(NEW);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 159 "imcc.l"
return(DEFINED);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 160 "imcc.l"
return(ADDR);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 161 "imcc.l"
return(GLOBAL);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 162 "imcc.l"
return(CLONE);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 163 "imcc.l"
return(STRINGV);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 164 "imcc.l"
return(CALL);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 165 "imcc.l"
return(SAVEALL);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 166 "imcc.l"
return(RESTOREALL);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 167 "imcc.l"
return(SHIFT_LEFT);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 168 "imcc.l"
return(SHIFT_RIGHT);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "imcc.l"
return(SHIFT_RIGHT_U);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "imcc.l"
return(LOG_AND);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 171 "imcc.l"
return(LOG_OR);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 172 "imcc.l"
return(LOG_XOR);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 173 "imcc.l"
return(RELOP_LT);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 174 "imcc.l"
return(RELOP_LTE);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "imcc.l"
return(RELOP_GT);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "imcc.l"
return(RELOP_GTE);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 177 "imcc.l"
return(RELOP_EQ);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 178 "imcc.l"
return(RELOP_NE);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 179 "imcc.l"
return(POW);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 181 "imcc.l"
{
        return read_macro(valp, interp);
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 185 "imcc.l"
{
        int c;

	c = yylex(valp, interp);
	if (c != STRINGC) return c;

	YYCHOP();
	include_file(str_dup(yytext + 1));
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 195 "imcc.l"
{
        char *label;

	if (valp) {
	    YYCHOP(); YYCHOP();

	    label = mem_sys_allocate(yyleng+10);
	    sprintf(label, "%s%d", yytext, frames->label);

	    valp->s = label;
	}

        return LABEL;
    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 210 "imcc.l"
{
        char *label;

	if (valp) {
	    YYCHOP();

	    label = mem_sys_allocate(yyleng+10);
	    sprintf(label, "%s%d", yytext, frames->label);

	    valp->s = label;
	}

	return IDENTIFIER;
    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 225 "imcc.l"
return(COMMA);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 227 "imcc.l"
{
	YYCHOP();  /* trim last ':' */
	DUP_AND_RET(valp,LABEL);
    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 232 "imcc.l"
{
        int type = get_pmc_num(interp, yytext+1);

        if (type) {
            char *buf = malloc(16);
	    sprintf(buf, "%d", type);
	    valp->s = buf;
	    return INTC;
	}
	if (!expand_macro(valp, interp, yytext+1))
            fataly(1, "", line, "unknown macro '%s'\n", yytext);
    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 245 "imcc.l"
{
	if (!is_def) {
		SymReg *r = find_sym(yytext);
		if (r && (r->type & (VTIDENTIFIER|VT_CONSTP))) {
		    valp->sr = r;
		    return VAR;
		}
	}
        valp->s = str_dup(yytext);
        return(is_op(interp, valp->s) ? PARROT_OP : IDENTIFIER);
    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 257 "imcc.l"
DUP_AND_RET(valp, FLOATC);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 258 "imcc.l"
DUP_AND_RET(valp, INTC);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 259 "imcc.l"
DUP_AND_RET(valp, INTC);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 260 "imcc.l"
DUP_AND_RET(valp, INTC);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 262 "imcc.l"
{
	valp->s = str_dup(yytext);
        return(STRINGC); /* XXX delete quotes, -> emit, pbc */
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 267 "imcc.l"
{
        valp->s = str_dup(yytext); /* XXX delete quotes, -> emit, pbc */
        return(STRINGC);
    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 272 "imcc.l"
DUP_AND_RET(valp, IREG);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 273 "imcc.l"
DUP_AND_RET(valp, NREG);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 274 "imcc.l"
DUP_AND_RET(valp, SREG);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 275 "imcc.l"
DUP_AND_RET(valp, PREG);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 277 "imcc.l"
/* skip */;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 279 "imcc.l"
{
        return yytext[0];
    }
	YY_BREAK
case YY_STATE_EOF(emit):
#line 283 "imcc.l"
{
        BEGIN (INITIAL);
        if (pasm_file) {
            pasm_file = 2;
            return EOM;
        }
        return 0;
    }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 292 "imcc.l"
yyterminate();
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 294 "imcc.l"
DUP_AND_RET(valp, ENDM);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 296 "imcc.l"
{
        line++;
        DUP_AND_RET(valp, '\n');
    }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 301 "imcc.l"
return LABEL;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 302 "imcc.l"
{
        char *label;
	char *name = macros[num_macros].name;

	if (yylex(valp, interp) != LABEL) yyerror("LABEL expected");

	if (valp) {
	    YYCHOP();

	    label = mem_sys_allocate(strlen(name) + yyleng + 15);
	    sprintf(label, "local__%s__%s__$:", name, yytext+1);

	    valp->s = label;
	}

	return LABEL;
    }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 320 "imcc.l"
{
        char *label;
	char *name = macros[num_macros].name;

	if (valp) {
	    label = mem_sys_allocate(strlen(name) + yyleng + 15);
	    sprintf(label, "local__%s__%s__$", name, yytext+2);

	    valp->s = label;
	}

	return IDENTIFIER;
    }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 334 "imcc.l"
/* skip leading ws */;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 335 "imcc.l"
DUP_AND_RET(valp, ' ');
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 336 "imcc.l"
DUP_AND_RET(valp, IDENTIFIER);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 337 "imcc.l"
DUP_AND_RET(valp, MACRO);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 338 "imcc.l"
DUP_AND_RET(valp, yytext[0]);
	YY_BREAK
case YY_STATE_EOF(macro):
#line 339 "imcc.l"
yyterminate();
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 341 "imcc.l"
ECHO;
	YY_BREAK
#line 1482 "imclexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 291 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 291 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 290);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 341 "imcc.l"


#ifdef yywrap
#undef yywrap
#endif

int yywrap() {
    /* Add code here to open next source file and start scanning
       yywrap returns 0 if scanning is to continue
    */
    yy_delete_buffer(YY_CURRENT_BUFFER);

    /* pop old frames */
    if (frames) {
	struct macro_frame_t *tmp;
	tmp = frames;
	frames = frames->next;
	destroy_frame(tmp);
	return 0;
    }

    return 1;
}

static struct macro_frame_t *
new_frame (void)
{
    static int label = 0;
    struct macro_frame_t *tmp;

    tmp = mem_sys_allocate_zeroed(sizeof(struct macro_frame_t));
    tmp->label = ++label;

    return tmp;
}

static void
scan_string (struct macro_frame_t *frame, const char *expansion)
{
    frame->buffer = YY_CURRENT_BUFFER;
    frame->next = frames;
    frames = frame;

    yy_scan_string(expansion);
}

static void
destroy_frame (struct macro_frame_t *frame)
{
    YY_BUFFER_STATE buffer;
    int i;

    buffer = frame->buffer;

    for (i = 0; i < frame->expansion.num_param; i++) {
	free(frame->expansion.name[i]);
    }

    mem_sys_free(frame);

    yy_switch_to_buffer(buffer);
}

static int
yylex_skip (YYSTYPE *valp, void *interp, const char *skip)
{
    int c;
    const char *p;

    do {
        c = yylex(NULL, interp);
        p = skip;
	while (*p && c != *p) p++;
    } while (*p != '\0');

    DUP_AND_RET(valp, c);
}

static int
read_params (YYSTYPE *valp, void *interp, struct params_t *params,
	     int need_id)
{
    int c;
    YYSTYPE val;
    char *current = strdup("");
    int len = 0;

    params->num_param = 0;
    c = yylex_skip(&val, interp, " \n");

    while(c != ')') {
	if (c == 0) yyerror ("Unexpected end of file");
	else if (c == ',') {
	    params->name[params->num_param++] = current;
	    current = strdup("");
	    len = 0;
	    c = yylex_skip(&val, interp, " \n");
	}
	else if (need_id && (*current || c != IDENTIFIER) && c != ' ') {
	    yyerror("macro parameter error");
	}
	else {
	    if (!need_id || c != ' ') {
		len += strlen(val.s);
		current = realloc(current, len + 1);
		strcat(current,val.s);
	    }
	    free(val.s);
	    c = yylex(&val,interp);
	}
    }
    params->name[params->num_param++] = current;

    if (valp) *valp = val;
    else free(val.s);

    return c;
}

static int
read_macro (YYSTYPE *valp, void *interp)
{
    int c;
    struct macro_t *m = macros + num_macros;
    int start_cond;

    temp_buffer[0]='\0';

    start_cond = YY_START;
    BEGIN(macro);

    c = yylex(NULL, interp);
    if (c != ' ') yyerror("macro error");

    c = yylex(valp, interp);
    if (c != IDENTIFIER) yyerror("macro error");

    m->name = valp->s;

    /* white space is allowed between macro and opening paren) */
    c = yylex_skip(valp, interp, " ");

    if (c == '(') {
	free(valp->s);

	c = read_params(NULL, interp, &m->params, 1);
	if (c != ')') yyerror("macro parameter: \")\" expected");

	c = yylex(valp, interp);
    }

    while (c != ENDM) {
	if (c == 0) yyerror("file ended before macro complete");

	strcat(temp_buffer, valp->s);
	free(valp->s);

        c = yylex(valp, interp);
    }
    free(valp->s);

    BEGIN(start_cond);

    macros[num_macros].expansion = str_dup(temp_buffer);

    num_macros++;
    return MACRO;
}

static char *
find_macro_param (const char *name)
{
    struct macro_frame_t *f;
    int i;

    for (f = frames; f; f = f->next) {
	if (f->params) {
	    for (i = 0; i < f->params->num_param; i++) {
		if (strcmp(f->params->name[i], name) == 0) {
		    return f->expansion.name[i];
		}
	    }
	}
    }

    return NULL;
}

static struct macro_t *
find_macro (const char* name)
{
    int i;

    for (i = 0; i < num_macros; i++) {
	if (strcmp(name, macros[i].name) == 0) return macros + i;
    }

    return NULL;
}

static int
expand_macro (YYSTYPE *valp, void *interp, const char *name)
{
    int c;
    struct macro_frame_t *frame;
    struct macro_t *m;
    const char *expansion;
    int start_cond;

    frame = new_frame();

    expansion = find_macro_param(name);
    if (expansion) {
	scan_string(frame, expansion);
	return 1;
    }

    m = find_macro(name);
    frame->params = &m->params;
    if (m) {
	/* whitespace can be savely ignored */
	do {
	    c = input();
	} while (c == ' ' || c == '\t');

	if (c != '(') {
	    unput(c);
	    if (m->params.num_param != 0) yyerror ("Missing macro parameter");
	    scan_string(frame, m->expansion);
	    return 1;
	}

	start_cond = YY_START;
	BEGIN(macro);

	read_params (NULL, interp, &frame->expansion, 0);

	BEGIN(start_cond);

	if (frame->expansion.num_param == 0 && m->params.num_param == 1) {
	    frame->expansion.name[0] = str_dup("");
	    frame->expansion.num_param = 1;
	}

	if (frame->expansion.num_param != m->params.num_param) {
	    yyerror ("Wrong number of macro arguments");
	}

	scan_string(frame, m->expansion);
	return 1;
    }

    return 0;
}

static void
include_file (const char *file_name)
{
    struct macro_frame_t *frame;
    FILE *file;

    frame = new_frame();

    file = fopen(file_name, "r");
    if (!file) yyerror ("file not found");

    scan_file (frame, file);
}

static void
scan_file (struct macro_frame_t *frame, FILE *file)
{
    frame->buffer = YY_CURRENT_BUFFER;
    frame->next = frames;
    frames = frame;

    yy_switch_to_buffer(yy_create_buffer(file, YY_BUF_SIZE));
}

/*
 * Local variables:
 * c-indentation-style: bsd
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * End:
 *
 * vim: expandtab shiftwidth=4:
 */
