# Copyright: 2001-2004 The Perl Foundation.  All Rights Reserved.
# $Id$

=head1 NAME

docs/pdds/pdd_template.pod - PDD Template

=head1 ABSTRACT

Summary of the contents of the PDD.

=head1 DESCRIPTION

Description of the subject.

=head1 IMPLEMENTATION

Implementation details.

=head1 ATTACHMENTS

Any associated documents.

=head1 FOOTNOTES

List of footnotes to the text.

=head1 REFERENCES

List of references.

=head1 VERSION

=head2 CURRENT

    Maintainer: 
    Class: 
    PDD Number:
    Version:
    Status: 
    Last Modified: 
    PDD Format: 1
    Language:

=head2 HISTORY

=over 4

=item version 1

None. First version

=back

=head1 CHANGES

=over 4

=item Version 1.0

None. First version

=back

