# !/usr/bin/perl -w
use strict;
use Digest::MD5 qw(&md5_hex);

open INTERP, "> interp_guts.h" or die "Can't open interp_guts.h, $!/$^E";

open OPCODES, "opcode_table" or die "Can't open opcode_table, $!/$^E";

print INTERP <<CONST;
/*
 *
 * interp_guts.h
 *
 * this file is autogenerated by build_interp_starter.pl
 *
 * Best not edit it
 */

#define BUILD_TABLE(x) do { \\
CONST

my $opcode_table;
my $count = 1;
while (<OPCODES>) {
    $opcode_table .= $_;
    chomp;
    s/#.*$//;
    s/^\s+//;
    next unless $_;
    my($name) = split /\s+/;
    my $num = $count;
    $num = 0 if $name eq 'end';
    print INTERP "\tx[$num] = $name; \\\n";
    $count++ unless $name eq 'end';
}
close OPCODES;
my $opcode_fingerprint = md5_hex($opcode_table);
print INTERP "} while (0);\n";


# Spit out the DO_OP function
print INTERP <<EOI;

#define DO_OP(w,x,y,z) do { \\
    x = (void *)z->opcode_funcs; \\
    (void *)y = x[*w]; \\
    w = (y)(w,z); \\
 } while (0);
EOI

# Spit out the OPCODE_FINGERPRINT macro
print INTERP <<EOI

#define OPCODE_FINGERPRINT "$opcode_fingerprint"
EOI
