
=head1 Deprecation in Parrot

This is a list of currently deprecated features of Parrot.
Every deprecation should have an associated RT ticket, but this
is not the case yet [RT#41226].

=head1 new object system

The object system of Parrot is being overhauled. This touches some opcode
and PIR syntax. So some deprecation can be found in pdd17_pmc.pod.

=head1 PGE::P6Regex and pgc.pir

In early 2007 there were a number of changes made to the Perl 6
regular expression syntax (as given by Synopsis 5).  The new
syntax is implemented via the PGE::Perl6Regex compiler, and the
PGE::P6Regex compiler is now deprecated in favor of the new
syntax.

Similarly, the pgc.pir compiler (for grammars) is deprecated
in favor of runtime/parrot/library/PGE/Perl6Grammar.{pir|pbc} .

=head1 Deprecated C APIs

Currently no C APIs are deprecated.

=head1 Deprecated methods

No methods are known to be deprecated.

=head1 Deprecated ops

From L<http://www.parrotcode.org/docs/ops/var.html>, the following ops are
deprecated:

=over 4

=item B<store_global>

=item B<find_global>

=item B<find_name>

There are several variants of some of the above ops; all are deprecated,
and are replaced by the ops {set,get}_[hll,root]_global.

=back

From L<http://www.parrotcode.org/docs/ops/experimental.html>, the following ops
are deprecated:

=over 4

=item B<new>(out PMC, in INT, in STR) (RT #47011)

The VTABLE method 'new_from_string' will be removed.

=back

They will be removed after the 0.5.0 release.

=head1 Deprecated Class Features

=over 4

=item 1

Type IDs will go away after 0.5.0.
Instead of:

  $P0 = new Integer

or

  $P0 = new .Integer

we are moving to use:

  $P0 = new 'Integer'

=item 2

The C<classname> op is deprecated and will be removed after the 0.5.0 release.
It's an exact duplicate of the string return variant of the C<typeof> op.

=item 3

The experimental C<instantiate> opcode is deprecated and will be removed after
the 0.5.0 release.

(The C<instantiate> vtable function becomes core in 0.5.0, but is accessed via
the "new" opcode for the PMCs that use it.)

=item 4

The C<getclass> opcode is deprecated (replaced by the C<get_class> opcode) and
will be removed after the 0.5.0 release.

=item 5

The C<get_mro> opcode is deprecated (replaced by C<inspect>) and will be
removed after the 0.5.0 release.

=item 6

The PMC union struct is deprecated and will be removed once all core PMCs have
been updated.

=back

=head1 Deprecated Exception Features

=over 4

=item 1

Attributes on exception objects will no longer be accessible by integer or
string key, use C<getattribute> and C<setattribute> instead. Slated for removal
in the 0.5.2 release.

=back

=head1 deprecated PIR syntax

=over 4

=item C<.HLL_map INTC, INTC> will become C<.HLL_map STRINGC, STRINGC>

As the dot-prefix type notation (for instance, '.Integer') is disappearing, the
C<.HLL_map> syntax will also be updated to take strings to indicate the types.
[RT#45453].


=item .namespace [ "a" .. "b" ]

IMCC currently allows for writing:

.namespace ["a" .. "b"]

This does not make sense, and this slicing syntax will be deprecated.

See [RT#46715]

=item .emit / .eom

The .emit and .eom directives that can be used to emit pure pasm instructions
in a PIR file, without using a .sub are deprecated, and will be removed afer
the 0.5.1 release.

See [RT#47846] for rationale.

=back

=head1 Deprecated compiler tools

=over 4

=item pgc.pir

The pgc.pir compiler for P6 grammars (pre-2007 regex syntax) is deprecated.
Switch to using the new Perl6Grammar.pir compiler instead, and the
Perl6Regex syntax.

=item compilers/PAST-pm

The compiler tools in compilers/PAST-pm/ and
runtime/parrot/library/Parrot/HLLCompiler.pir are deprecated
in favor of the new versions in the Parrot Compiler Toolkit
( compilers/pct/ ).  In particular, the PAST representation in
PCT follows the specification given by pdd26 .

=back

=head1 FUTURE changes

Not yet deprecated, but it's recommended to use the new syntax and
gradually change the old.

=over 4

=item Assignment syntax with opcodes [RT#36283]

When the first argument of an opcode is C<OUT>, then the assignment syntax
will be allowed, as it is today.

In any other case (i.e. C<INOUT>, C<IN>), this will become
a syntax error. For example:

    $S0 = print
    $P0 = substr 1, 2, "x"

Will have to be:

    print $S0
    substr $P0, 1, 2, "x"

=back
