# $Id$

=head1 Deprecation in Parrot

This is a list of currently deprecated features of Parrot.  Every deprecation
has an associated RT ticket.  Each item indicates the last release it's
guaranteed to appear in.  Items marked with a release of ??? are still
deprecated, but a firm deadline for their removal has not yet been established.

When deprecated items are removed, all usage of the feature in the
repository should be updated or removed; including documentation.

=head1 vtable entries

=over 4

=item * C<get_attr> [post 0.5.2]

See RT #48583.

=item * C<set_attr> [post 0.5.2]

See RT #48585.

=item * C<type_keyed> [post 0.5.2]

See RT #48577.

=item * C<type_keyed_int> [post 0.5.2]

See RT #48579.

=item * C<type_keyed_str> [post 0.5.2]

See RT #48581.

=item * C<type> [post 0.5.2]

See RT #48567.

=item * C<new_from_string> [post 0.5.0]

See RT #47011.

=back

=head1 Opcodes

=over 4

=item * C<pioctl> [post 0.5.1]

See RT #48589.

=item * C<store_global> [post 0.5.0]

See RT #48016. Replace usage with set_[hll,root]_global variants.

=item * C<find_global> [post 0.5.0]

See RT #48018. Replace usage with get_[hll,root]_global variants.

=item * C<new>(out PMC, in INT, in STR) [post 0.5.0]

See RT #47011.

=item * C<getclass> [post 0.5.0]

See RT #47972. Future use should use the C<get_class> opcode.

=item * C<get_mro> [post 0.5.0]

See RT #47976.

=item * C<getfd> [post 0.5.1]

See RT #48310.

=back

=head1 Class Features

=over 4

=item * Integer Type IDs [post 0.5.0]

See RT #48024. Instead of C<$P0 = new Integer> or C<$P0 = new .Integer>,
use the following syntax, which works for both PMCs and objects.

  $P0 = new 'Integer'

=item * PMC union struct [post 0.5.0]

See RT #48014. This will be removed once all core PMCs have been updated.

=item * Super PMC [post 0.6.2]

See RT #53968.

=back

=head1 Exceptions

=over 4

=item * Keyed access to exception attributes [post 0.5.1]

See RT #48012. Attributes on exception objects will no longer be accessible
by integer key, use C<getattribute> and C<setattribute> instead.

=item * 'push_exception' function [post 0.6.2]

Is deprecated, replaced by C<Parrot_cx_add_handler> (a method call to
C<add_handler> on the concurrency scheduler object).

=item * 'pop_exception' function [post 0.6.2]

Is deprecated, replaced by C<Parrot_cx_delete_handler_typed> (a method call to
C<delete_handler> on the concurrency scheduler object).

=item * 'count_exception_handlers' function [post 0.6.2]

Is deprecated, replaced by C<Parrot_cx_count_handlers_typed> (a method call to
C<count_handlers> on the concurrency scheduler object).

=item * 'get_exception_handler' function and 'get_eh' opcode [post 0.6.2]

Are deprecated, exception handler lookup by index is no longer supported.

=item * 'get_all_exception_handlers' function and 'get_all_eh' opcode [post 0.6.2]

Are deprecated, access to the exception handler list should be performed
through the concurrency scheduler.

=item * 'throwcc' opcode [post 0.6.2]

Is deprecated, replaced by the C<throw> opcode (the single argument form of
'throwcc' was already identical to 'throw').

=item * 'internal_exception' function [post 0.6.2]

Is deprecated, replaced by the C<exit_fatal> function.

=back

=head1 PIR syntax

=over 4

=item * C<<.namespace <identifier> >> syntax [post 0.5.1]

See RT #48737.

=item * Use of C<::> in identifiers [post 0.5.1]

See RT #48735.

=item * C<.namespace [ "a" .. "b" ]> [post 0.5.0]

See RT #46715.

=item * vtable name .constants and __vtable overrides [post 0.5.2]

See RT #48877.

=item * Assignment syntax with opcodes [post ???]

See RT #36283.  When the first argument of an opcode is C<OUT>, then
the assignment syntax will be allowed, as it is today.

In any other case (i.e. C<INOUT>, C<IN>), this will become
a syntax error. For example:

    $S0 = print
    $P0 = substr 1, 2, "x"

Will have to be:

    print $S0
    substr $P0, 1, 2, "x"


=back

=head1 Parrot Compiler tools

=head2 Parser Grammar Engine (PGE)

=over 4

=item Non-capturing C<< <?foo> >> is now C<< <.foo> >>

(See RT#53834)

Synopsis 5 changes the syntax for non-capturing subrules from
C<< <?foo> >> to C<< <.foo> >>.  According to S05, the
C<< <?foo> >> syntax is now used to indicate a zero-width
assertion.  So, grammars that have been using C<< <?foo> >>
for non-capturing subrules need to convert to the new syntax.

PGE will continue to support the non-capture interpretation
of C<< <?foo> >> until the May 2008 release, after which it
will be removed.

=item Change argument handling of C<< <foo: text> >>

(See RT#53606.)

Synopsis 5 changes the handling of arguments after a colon
in subrule invocations so that  C<< <foo: text> >> must
now be written as C<< <foo: 'text'> >>.

For the foreseeable future PGE will support both syntaxes,
but the obsolete C<< <foo: text> >> syntax may disappear
at any time after the June 2008 release.

=back

=head2 Capture-based objects

=over 4

=item get_array, get_hash, get_scalar deprecations [post 0.6.2]

See RT#54000.  The 'get_array', 'get_hash', and 'get_scalar'
methods are now called 'list', 'hash', and 'item' respectively.

=back

=cut
