# Parrot is Copyright (C) 2001-2008, Parrot Foundation.

=head1 NAME

DONORS

=head1 DONORS

We would like to thank the following people and institutions,
whose financial contributions help support the development of Parrot.

=over 4

=item * The Perl Foundation

L<http://perlfoundation.org>

=item * NLnet Foundation

L<http://nlnet.nl>

=item * The Mozilla Foundation

L<http://www.mozilla.org>

=item  * Best Practical

L<http://bestpractical.com>

=item  * ActiveState

L<http://activestate.com>

=item  * BBC

L<http://bbc.co.uk>

=back

=head1 ERRATA

Information will be added to this file as it becomes available.
For errors and omissions, please contact the directors of the Parrot
Foundation <directors at lists.parrot.org>

=cut
