=pod

=head0 ERRATA

Parrot is continually evolving and the book does not keep pace. This is a list
of known defects in the book. We'll clean up the book as soon as possible, but
in the meantime, enjoy this map of some of the rough patches.

=head1 Removed or Deprecated Features

=over 4

=back

=cut
