package Configure::Step;

use strict;
use vars qw($description @args);
use Parrot::Configure::Step;
use ExtUtils::Manifest qw(manicheck);

$description="Generating and checking MANIFEST...";

@args=qw(nomanicheck);

sub runstep {
  return if $_[0];

  open(MFT, ">MANIFEST") or die "create MANIFEST: $!";
  print MFT "# DO NOT EDIT - This file is autogenerated from MANIFEST.detailed\n";
  open(MFTD, "MANIFEST.detailed") or die "open MANIFEST.detailed: $!";
  while(<MFTD>) {
      chomp;
      s/^\s+//;
      s/\s+$//;
      next if /^\s*\#/;
      next if length($_) == 0;
      my ($meta, $src, $dest) = split(/\s+/);
      next if $meta =~ /^\*/;
      print MFT "$src\n";
  }
  close MFTD;
  close MFT;

  my(@missing)=manicheck();

  if(@missing) {
     print <<"END";

Ack, some files were missing!  I can't continue running
without everything here.  Please try to find the above
files and then try running Configure again.

END

    exit 1;
  }
}
