# Copyright (C) 2001-2012, Parrot Foundation.

=pod

=head1 NAME

examples/sdl/tetris/README.pod - Readme file for the tetris example. 

=head1 DESCRIPTION

To run this example, execute the following command from the Parrot directory:

=over 4

./parrot examples/sdl/tetris/tetris.pir

=back

=head1 COPYRIGHT

Copyright (C) 2001-2012, Parrot Foundation.

=cut

