# $Id$

=head1 Eclectus

Eclectus aims to be a Scheme to PIR compiler implemented in Scheme.
It is based on Abdulaziz Ghuloums compiler tutorial.

=head1 Status

Starting to work on section 1.4 Conditional Expressions

=head1 Testing

Tests are written in Scheme. The test-driver is derived from the tutorial, 
tweaked to emit TAP.
There are Perl 5 wrappers for the scheme test scripts, in order to allow
unified languages testing.

The F<t/*.pl> scripts are used in unified languages testing. They
are executing the respective F<t/*.t> Scheme scripts. In
unified languages testing the Eclectus tests are skipped, when
the is no 'petite 7.3' around.

=head1 TODO

- allow test-description per test case
- In the longterm, Eclectus should become self-hosting

=head1 AUTHOR

Bernhard Schmalhofer

=head1 SEE ALSO

L<http://en.wikipedia.org/wiki/Eclectus>

L<http://www.cs.indiana.edu/%7Eaghuloum/compilers-tutorial-2006-09-16.pdf>

L<http://scheme2006.cs.uchicago.edu/11-ghuloum.pdf>

L<http://www.cs.indiana.edu/%7Eaghuloum/ikarus/index.html>

L<http://www-pu.informatik.uni-tuebingen.de/users/sperber/info-i-9900/material/konstruktion/konstruktion-10.ps>
