## $Id$

=head1 Things that NQP needs

This list is based on discussions with pmichaud and unimplemented
items in the grammar, C<src/Grammar.pg>.

=head2 Code

=over 4

=item * return

Return needs to work on an exception model, and will likely require 
PAST/POST changes to support it.

=item * Namespace support

=item * Named argument (not param) support

This will be added to PAST::Var by allowing parameter nodes to
have a 'named' attribute.

=back

=head2 Tests

=over 4

=item * Method ops

This may be very hard since we don't have any methods!

=item * Hash key access C<$E<lt>someKeyE<gt>>

=item * List member access C<$[index]>

=item * Match variable access C<$/>

=item * Scalar context $( ... )

=item * List context @( ... )

=back
