=head1 TABLE OF CONTENTS

This is a list of documents relating to the .NET CLI => Parrot Intermediate
Representation translator.

=head2 USING THE TRANSLATOR

=over 4

=item L<introduction.pod>: Introduction

=item L<building.pod>: Building

=item L<running.pod>: Running the EXE/DLL => PBC translator

=item L<pirinterface.pod>: Loading .NET classes directly from PIR code

=back

=head2 HACKING ON THE TRANSLATOR

=over 4

=item L<overview.pod>: Overview of the system

=item L<pmcs.pod>: The .NET metadata PMCs

=item L<metadatatranslator.pod>: Translating .NET class metadata to PIR

=item L<rulesfile.pod>: The translation rules file format

=item L<translatorbuilder.pod>: The translator builder

=item L<stacktoregister.pod>: Notes on stack to register mapping

=back

=head2 CONSTRUCT TRANSLATION DETAILS

=over 4

=item L<constructs/arrays.pod>: Arrays

=item L<constructs/calling.pod>: Calling

=item L<constructs/exceptions.pod>: Exceptions

=item L<constructs/managedpointers.pod>: Managed Pointers

=item L<constructs/oop.pod>: OOP

=item L<constructs/valuetypes.pod>: Value Types

=item L<constructs/builtintypes.pod>: Built in types (TO DO)

=item L<constructs/strings.pod>: Strings (TO DO)

=item L<constructs/typechecking.pod>: Type Checking (TO DO)

=item L<constructs/visibility.pod>: Visibility Modifiers (TO DO)

=back

=head2 FURTHER REFERENCES

=over 4

=item L<http://www.jnthn.net/papers/2006-cam-net2pir-dissertation.pdf>: J.Worthington's Dissertation Paper on net2pbc

=item L<http://en.wikipedia.org/wiki/Common_Language_Infrastructure>: Wikipedia on CLI

=item L<http://www.ecma-international.org/publications/standards/Ecma-335.htm>: "Standard ECMA-335, Common Language Infrastructure (CLI)"

=item L<http://www.iso.org/iso/en/CatalogueDetailPage.CatalogueDetail?CSNUMBER=42927>: "ISO/IEC 23271, Common Language Infrastructure"

=item L<http://www.go-mono.com/>: MONO, the Open Source CLI implementation

=item L<http://www.microsoft.com/downloads/details.aspx?FamilyID=8c09fd61-3f26-4555-ae17-3121b4f51d4d>: Microsoft's Shared Source CLI

=item L<stacktoregister.pod> contains references to SRM (C<Stack to Register Mapping>) issues.

=back
