# $Id$

=head1 NAME
 
Plumhead - Introduction

=head1 What is Plumhead?

An incomplete implementation of PHP on Parrot.
Plumhead is short for Plum-headed Parakeet.

=head1 Goals

Provide a side by side comparison for different implementation
strategies of PHP on Parrot.

=over

=item php       - the reference implementation PHP 5.2.0

=item phc       - XSLT munges output from phc, started

=item antlr3    - ANTLR3, converted from languages/bc, started

=item partridge - Parrot compiler toolchain, started

=item yacc      - with lex and yacc, planned

=item perl5re   - Perl5.10 regexes, planned

=back

=head1 Status

36 out of 2692 tests in the PHP 5.2.0 test suite pass for the phc variant.

=head1 Dependencies

=over

=item phc

xsltproc and phc need to be in PATH.

=item antlr3

ANTLR3 generating Java code.

=item yacc

lex and yacc, or flex and bison

=item perl5re

Perl5.10

=back

=head1 Author

Bernhard Schmalhofer - <Bernhard.Schmalhofer@gmx.de>

=head1 SEE ALSO

=over 4

=item L<http://rakudo.org/parrot/index.cgi?plumhead>

=item L<http://phpcompiler.org/>

=item L<http://en.wikipedia.org/wiki/Document_Object_Model>

=item L<http://en.wikipedia.org/wiki/Abstract_syntax_tree>

=item L<http://en.wikipedia.org/wiki/XSLT>

=item L<http://search.cpan.org/dist/parrot/docs/glossary.pod>

=item L<http://perl.overmeer.net/xml-compile/>

=item L<http://en.wikipedia.org/wiki/Plum-headed_parakeet>

=item L<http://www.parrotcode.org/docs/compiler_tools.html>

=item L<http://www.antlr.org/v3/index.html>

=back

=cut
