#! perl
# $Id$

# pragmata
use strict;
use warnings;
use 5.008;
use lib qw( languages/scheme/lib lib );

use Scheme;

sub usage {
  print <<"END_USAGE";
usage: $0 <file.scheme>
END_USAGE

  exit;
}

defined $ARGV[0] or usage();
$ARGV[0] =~ m/\.scheme$|\.scm$/i or usage();

print Scheme->new($ARGV[0])->compile();
