#! perl

# $Id$

use FindBin;
use lib qw( . lib ../lib ../../lib );
use File::Spec;
use Getopt::Long qw(:config pass_through);
use Data::Dumper;

my %harness_args = (
    language => 'cardinal',
    compiler => 'cardinal.pbc',
);

GetOptions(
        'tests-from-dir=s' => \my $test_dir,
    );
if ($test_dir) {
my @files = grep m/^[^-]/, @ARGV;
push @files, "t/$test_dir/*.t";

$harness_args{files} = \@files;
}

eval 'use Parrot::Test::Harness %harness_args';

