#!/bin/sh

# sh tools/dev/mk_packfile_pbc
#
# generate t/native_pbc/*.pbc for testing Packfile* PMCs.

for type in integer number string
do
    ./parrot -o t/native_pbc/$type.pbc t/native_pbc/testdata/$type.pasm \
        && echo "t/native_pbc/$type.pbc updated"
done
type=annotations
./parrot -o t/native_pbc/$type.pbc t/native_pbc/testdata/$type.pir \
    && echo "t/native_pbc/$type.pbc updated"
type=
