# Copyright (C) 2011, Parrot Foundation

=pod

=head1 NAME

docs/mans/vmspec/toc.pod - Table of Contents to the Parrot Virtual Machine 
Specification. 

=head1 DESCRIPTION

=over 4

=item Preface

=item Table of Contents

=item 1.  Introduction

=over 3

=item 1.1: History

=item 1.2: Overview

=back

=item 2.  The Winxed Programming Language Concepts

=item 3.  The Structure of the Parrot Virtual Machine

=item 4.  The bytecode File Format

=item 5.  Loading, Linking, and Initializing 

=item 6.  The Parrot Virtual Machine Instruction Set

=item 7.  Compiling for the Parrot Virtual Machine

=item 8.  The Memory Internals

=item 9.  The Parrot Virtual Machine Threading System

=item 10. Opcode Mnemonics by Opcode

=item Appendix A. The NQP (Not Quite Perl) Programming Language

=item Appendix B. The Parrot Intermediate Representation Language

=item Glossary

=item Bibliography

=item Index

=back

=head1 COPYRIGHT

Copyright (C) 2001-2011, Parrot Foundation.

=cut
