# $Id$

=head1 NAME
 
Pipp - Introduction

=head1 What is Pipp?

Pipp aims to be a complete implementation of PHP on Parrot.
In short, Pipp in Parrot's PHP.

=head1 Goals

Implement PHP.
Support well behaving PHP extensions.
See also L<../ROADMAP>.

=head1 Divergences of Pipp

A listing of things that Pipp does differently from the standard PHP.

=over 4

=item builtin function pipp_defined().

=item Loading of Parrot libs will be supported.

=item Support for global variable $INC, list of included files.

=item No old style constructors, where the constructor is named after the class.

=item Only bracketed version of namespaces. No check for unnamespaced code.

=item 'const' outside a declared namespace is allowed.

=back

=head1 Implementation

Pipp is based on the Parrot Compiler Toolkit. See L<internals.pod> for details.

=head1 Status

No current status available.

=head1 Dependencies

=over

=item Parrot 0.8.2.

=back

=head1 Author

Bernhard Schmalhofer - <Bernhard.Schmalhofer@gmx.de>

=head1 SEE ALSO

=over 4

=item L<http://pipp.org>

=item L<http://www.perlfoundation.org/parrot/index.cgi?pipp>

=item L<http://phpcompiler.org/>

=item L<http://en.wikipedia.org/wiki/Abstract_syntax_tree>

=item L<http://en.wikipedia.org/wiki/Plum-headed_parakeet>

=back

=cut
