# $Id$

=head1 NAME
 
Pipp - Testing

=head1 Testsuite

For testing the test-suite from PHP 5.3 is used.
For sanity checking there are also few tests in
below the directory subdirs of F<pipp/t>.
These tests are executed by 'make test'.

Run individual tests e.g.:
  
  perl t/harness --verbose t/in_php/01_sea_only.t

=head1 How to run the PHP test suite

The testscript from the PHP 5.3 distribution is prepared to test other PHP implementations.
Something like this worked for me under Linux.

  # build Parrot
  cd ~/devel/Parrot/trunk
  perl Configure.pl && make

  # build Pipp
  cd languages/pipp
  make pipp

  # build PHP 5.3
  cd ~/devel/PHP/
  wget http://snaps.php.net/php5.3-200807221230.tar.gz
  tar xvzf php5.3-200807221230.tar.gz
  cd php5.3-200807221230/
  ./configure
  make

  # configure run-tests.php
  export PARROT_HOME=/home/bernhard/devel/Parrot/trunk
  export TEST_PHP_EXECUTABLE=$PARROT_HOME/languages/pipp/pipp
  export TEST_PHP_CGI_EXECUTABLE=$PARROT_HOME/languages/pipp/pipp
  # export PIPP_VARIANT=pct
  # export PIPP_VARIANT=phc
  export NO_INTERACTION=1

  # run the test-suite
  ./sapi/cli/php run-tests.php -v --keep-all | tee run-tests.log
  
Good luck.

=head1 Author

Bernhard Schmalhofer - <Bernhard.Schmalhofer@gmx.de>

=cut
