#!/usr/bin/perl

# Copyright (C) 2006-2007, The Perl Foundation.
# $Id$

BEGIN {
    # Check that we have the WMLScript compiler.
    my $check = `wmlsc -h`;
    unless ($check =~ /wmlsc/) {
        die "You need the WMLScript compiler in your path to build the test.\n\tcpan WAP::wmls\n";
    }
}

use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'WMLScript';

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 100
# End:
# vim: expandtab shiftwidth=4:

