#! perl

# $Id$

# pragmata
use strict;
use warnings;
use 5.008;

use lib qw( . lib ../lib ../../lib ../../lib );
use Parrot::Test::Harness language => 'Pod',
                          compiler => 'pod.pbc';

