# Copyright (C) 2005-2012, Parrot Foundation.

=pod

=head1 NAME

ports/ubuntu/README.pod - Readme file for the Ubuntu Parrot packages. 

=head1 DESCRIPTION

The Ubuntu Parrot packages are currently merged directly from Debian,
with no added changes, so these files are unused. They are kept here
for reference in building test packages in the Personal Package
Archive, and in case Ubuntu-specific packages are needed in the
future.

=head1 COPYRIGHT

Copyright (C) 2005-2012, Parrot Foundation.

=cut
