# Copyright (C) 2001-2012, Parrot Foundation.

=pod

=head1 NAME

tools/README.pod - Readme file for the 'tools/' top-level directory. 

=head1 DESCRIPTION

This directory contains multiple subdirectories which are outlined as follows:

=over 4

=item F<build/>

This subdirectory contains programs, templates, and configuration files
invoked by the default 'make' target I<e.g.,> 'make all', with or without
command-line options, during the Parrot build process.

=item F<dev/>

This subdirectory contains programs, templates, and configuration files found
useful to Parrot developers, excluding those which are (1) invoked via the
default 'make' target I<e.g.,> 'make all' or (2) invoked by 'make install' or
'make install-dev'.

=item F<docs/>

This subdirectory contains programs, templates, and configuration files found
useful for working with or for the building of Parrot's documentation.

=item F<install/>

This subdirectory contains programs, templates, and configuration files
found useful for the post-installation of Parrot, I<e.g.,> smoke reports.

=item F<release/>

This subdirectory contains programs, templates, and configuration files
invoked by 'make install' or 'make install-dev'.

=back

=head1 COPYRIGHT

Copyright (C) 2012, Parrot Foundation.

=cut
