#! perl

# $Id$

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../../../lib";

use Parrot::Test::Harness
    language => 'nqp',
    exec     => [ '../../../parrot', 'nqp.pbc' ],
    files    => [ '../t/*.t' ];
