#
# This makefile is to generate a parrot PDF document. You can use it with:
#  > make -f Makefile.pdf
#  > make -f Makefile.pdf <target>
# It will not work on Windows. It call a script which use a specific Unix
# command. May be that will be changed.
#
PERL  		 = /usr/bin/perl
MKPATH           = $(PERL) -MExtUtils::Command -e mkpath
CHAPTERS         = $(shell $(PERL) ../tools/docs/filename_and_chapter.pl --print)
M_CHAPTERS       = $(shell $(PERL) ../tools/docs/filename_and_chapter.pl --b_out)


default: build/parrot-book.pdf

release: build/parrot-book.pdf
	cp build/parrot-book.pdf build/parrot-book-$$(date +"%Y.%m").pdf

build/parrot-book.pdf: $(CHAPTERS) ../tools/docs/book-to-latex.pl
	$(MKPATH) build/modified_pod
	$(PERL) ../tools/docs/filename_and_chapter.pl
	$(PERL) ../tools/docs/book-to-latex.pl $(M_CHAPTERS) > build/parrot-book.tex
	cd build && pdflatex parrot-book.tex && pdflatex parrot-book.tex

clean: 
	rm -rf build

# vim: set noexpandtab
