=head1 NAME

docs/parrothist.pod - Parrot Release History

=head1 DESCRIPTION

This document records Parrot source code releases, and their release managers.

=head1 RELEASE MANAGERS

Simon Cozens, Jeff Goff, Steve Fink, Leo Toetsch, Chip Salzenberg, Jerry Gay,
Patrick Michaud, Will "coke" Coleda, Matt Diephouse, chromatic, Allison Randal,
Jonathan Worthington, Bob Rogers, Bernhard Schmalhofer, Andrew Whitworth,
Francois Perrad, Jonathan Leto, Michael Hind.


=head1 THE RECORDS

Starred release numbers indicate supported releases.

 Release     Release        Date            Release name
 Manager
 ===========================================================================

 Simon       0.0.1          2001-Sep-10     n/a
             0.0.2          2001-Oct-05     n/a
             0.0.3          2001-Dec-08     n/a
             0.0.4          2002-Mar-19     n/a

 Jeff        0.0.5          2002-Apr-16     n/a
             0.0.6          2002-Jun-04     n/a
             0.0.7          2002-Jul-18     "Percy"
             0.0.8          2002-Sep-01     "Octarine"
             0.0.8.1        2002-Sep-01     (bugfix release)

 Steve       0.0.9          2002-Dec-19     "Nazgul"
             0.0.10         2003-Mar-16     "Juice"
             0.0.11         2003-Sep-20     "Dubloon"
             0.0.11.2       2003-Sep-22     (bugfix release)

 Leo         0.0.13         2003-Oct-31     "Screaming Pumpkin"
             0.1.0          2004-Feb-29     "Leaping Kakapo"
             0.1.1          2004-Oct-09     "Poicephalus"
             0.1.2          2005-Mar-06     "Phoenix"
             0.2.0          2005-May-08     "NLnet"
             0.2.1          2005-Jun-04     "APW"
             0.2.2          2005-Jul-03     "Geeksunite"
             0.2.3          2005-Aug-05     "Serenity"
             0.3.0          2005-Oct-01     "Alex"
             0.3.1          2005-Nov-06     "Wart"
             0.4.0          2005-Dec-04     "Luthor"
             0.4.1          2006-Jan-08     "Foghorn Leghorn"
             0.4.2          2006-Feb-22     "GPW"
             0.4.3          2006-Apr-02     "Cold Conure"
             0.4.4          2006-May-14     "Feather"
             0.4.5          2006-Jun-19     n/a

 Chip        0.4.6          2006-Aug-08     n/a
             0.4.7          2006-Nov-14     "Caique"

 Jerry       0.4.8b         2007-Jan-16     "Eponymous"
 Patrick     0.4.9          2007-Feb-22     "Socorro"
 coke        0.4.10         2007-Mar-20     "Release Formerly Known as Prince"
 Matt        0.4.11         2007-Apr-17     "Tax Bird"
 chromatic   0.4.12         2007-May-15     "Of The Caribbean"
 Allison     0.4.13         2007-Jun-19     "Clifton"
 Jerry       0.4.14         2007-Jul-17     "Now, with Seat Belts!"
 Patrick     0.4.15         2007-Aug-22     "Augean Stable"
 Jerry       0.4.16         2007-Sep-18     "A Farewell to Alex"
 coke        0.4.17         2007-Oct-17     "Two for Finching"

 chromatic   0.5.0          2007-Nov-20     "Caulked Snack"
 Jonathan    0.5.1          2007-Dec-18     "Hatachi"
 Bob         0.5.2          2008-Jan-15     "P.e. nipalensis"
 Patrick     0.5.3          2008-Feb-20     "Way of the Parrot"

 Barney      0.6.0          2008-Mar-18     "P&P"
 Jerry       0.6.1          2008-Apr-15     "Bird of Paradise"
 chromatic   0.6.2          2008-May-20     "Reverse Sublimation"
 smash       0.6.3          2008-Jun-17     "Beautiful Parrot"
 Barney      0.6.4          2008-Jul-15     "St. Vincent Amazon"

 Bob         0.7.0          2008-Aug-19     "Severe Macaw"
 Patrick     0.7.1          2008-Sep-16     "Manu Aloha"

 Jerry       0.8.0          2008-Oct-21     "Pareto Principle"
 chromatic   0.8.1          2008-Nov-18     "Tio Richie"
 Whiteknight 0.8.2          2008-Dec-16     "Feliz Loro"

 chromatic   0.9.0          2009-Jan-20     "From Outer Space"
 kjs         0.9.1          2009-Feb-17     "Final Countdown"

 Allison     1.0.0 *        2009-Mar-17     "Haru Tatsu"
 Francois    1.1.0          2009-Apr-21     "Half-moon Conure"
 Infinoid    1.2.0          2009-May-19     "Bird Brain"
 Whiteknight 1.3.0          2009-Jun-16     "Andean Swift"

 cotto       1.4.0 *        2009-Jul-21     "Mundo Cani"
 Whiteknight 1.5.0          2009-Aug-18     "TEH PARROTZ!"
 Jerry       1.6.0          2009-Sep-15     "half-pie"
 dukeleto    1.7.0          2009-Oct-20     "African Grey"
 Barney      1.8.0          2009-Nov-17     "Zygodactyly"
 Gerd        1.9.0          2009-Dec-15     "Blue-fronted Amazon"

 chromatic   2.0.0 *        2010-Jan-19     "Inevitable"
 darbelo     2.1.0          2010-Feb-16     "As Scheduled"
 coke        2.1.1          2010-Feb-19     (bugfix release)
 cotto       2.2.0          2010-Mar-16     "Like Clockwork"

 Gerd        2.3.0 *        2010-Apr-20     "Samoan Lory"
 Whiteknight 2.4.0          2010-May-18     "Sulfer Crest"
 Gerd        2.5.0          2010-Jun-15     "Cheops"

 coke        2.6.0 *        2010-Jul-20     "Red-rumped"
 mikehh      2.7.0          2010-Aug-17     "Australian King"
 Gerd        2.8.0          2010-Sep-21     "Tui Parakeet"

 Gerd        2.9.0 *        2010-Oct-19     "Red-masked"
 cotto       2.9.1          2010-Oct-19     (bugfix release)
 tcurtis     2.10.0         2010-Nov-16     "Pesquet's"
 Gerd        2.10.1         2010-Nov-18     (bugfix release)
 Whiteknight 2.11.0         2010-Dec-21     "At The ROFLBBQ"

 cotto       3.0.0 *        2011-Jan-18     "Beef Stew"
 mikehh      3.1.0          2011-Feb-15     "Budgerigar"
 Gerd        3.2.0          2011-Mar-15     "Nanday Parakeet"

 Whiteknight 3.3.0 *        2011-Apr-19     "Fire in the Sky"
 Gerd        3.4.0          2011-May-17     "Pacific Parakeet"

=cut
